modLoader="javafml"

loaderVersion="[36,)"

license="All rights reserved"

issueTrackerURL="https://github.com/KingOfTheGamesYT/Random-Structure-Land/issues"

[[mods]]

modId="random_structure_land"

version="1.0.0"

displayName="Random Structure Land"

logoFile="Random_Structure_Land_Logo.png"

credits="Thanks for this mod goes to CaptainSparklez for giving me the idea"

authors=["RedRoseWarrior1 aka DevMaster1015"]

description='''
Randomnizes all structures in Minecraft
'''

# Base Forge
[[dependencies.random_structure_land]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

# Base Minecraft
[[dependencies.random_structure_land]]
    modId="minecraft"
    mandatory=true
versionRange="[1.16.5,1.17]"
    ordering="NONE"
    side="BOTH"
